// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sloahjskzvarqomsdyqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsb2FoanNrenZhcnFvbXNkeXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDYzNTMsImV4cCI6MjA2MDE4MjM1M30.kVFFtDUuakHfLOFqRuOSOMw1-mLob6cZafdEAR31v80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);